coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 60%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true

ignore:
  - "tests/**"
